### ISSUE TITLE
The new site http://asciiflow.com/ does not work

### ISSUE THREAD

**Issue by asmwarrior** [lewish/asciiflow2-issues#13]
Hi, I have Firefox 29.0.1, I can't event draw a line in the new site: http://asciiflow.com/
When I click the "line" button, and try to draw a line in the canvas using the mouse click or drag, nothing happens.
But the old site: http://stable.ascii-flow.appspot.com/#Draw still works OK.

**Comment by lewish** [comment]
I have no problems with the latest firefox, feel free to re-open if you still have problems.
