### ISSUE TITLE
Arrow to line becomes plus

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [lewish/asciiflow2-issues#21]
I'd like to point with arrow to line or rectangle.
If I drag an arrow, up to one character apart from line, it remains arrow: 
![screen shot 2014-06-20 at 2 49 39 pm](https://cloud.githubusercontent.com/assets/6518064/3339690/03ba1bf0-f871-11e3-930b-68a5757ac437.png)
But when I try to do: |< 
It becomes: +-
![screen shot 2014-06-20 at 2 52 17 pm](https://cloud.githubusercontent.com/assets/6518064/3339712/64dd71ac-f871-11e3-88cc-2b2d8fdb6d18.png)
It's very annoying. I don't understand why arrow enforce its logic even in manual copy/paste mode.

**Comment by nowox** [comment]
+1

**Comment by lewish** [comment]
This is actually working as intended, you need to use the arrow tool instead of the line tool from the menu and it will do as you are expecting.

**Comment by nowox** [comment]
Sorry, I don't agree with you. Take simply this example:

[image: Inline image 1]
