### ISSUE TITLE
Chinese characters are not properly displayed

### ISSUE THREAD

**Issue by gfreezy** [lewish/asciiflow2-issues#25]
They should take only unit while the should take two, collapsing each other.

![image](https://cloud.githubusercontent.com/assets/510012/3534048/94f86bda-07df-11e4-9fc1-568b2be95f56.png)

**Comment by lewish** [comment]
I had the same problem with asciiflow 1. If someone can tell me how monospace chinese characters work, I'm all ears, but as far as I know, it's just not possible...

**Comment by warmhug** [comment]
I'm sorry, It can't be resolved yet? So, I can't use it :(
