### ISSUE TITLE
Share the diagram

### ISSUE THREAD

**Issue by mikaa123** [lewish/asciiflow2-issues#37]
I would love to be able to copy/paste the URL of the diagram I am working on to share it.

With that said, I **love** asciiflow, and use it all the time. ;)

cheers :beers: !

**Comment by lewish** [comment]
Hi, we depend on Drive for sharing, if you save your diagram to drive, you can then share it with others, and continue to make updates to it etc. Unfortunately no way to do collaborative editing at the moment.
